### ISSUE TITLE
Which BSD licence?

### ISSUE THREAD

**Issue by damiandixon** [jihankim/KnobControl#2]
Hi there are several BSD licences, please see:

[https://en.wikipedia.org/wiki/BSD_licenses](url)

Could you please indicate which one you wish to use for this library.

I quite like the 2 or 3 clause variant of the BSD licence. Though ideally I prefer the MIT licence.

I quite like the KnobControl for its simplicity of look. Thank you for sharing.

**Comment by jihankim** [comment]
@damiandixon Hi. Thanks for you comment. As you can see, I have been just put it in github and done nothing so long time. Well, as you said you prefer MIT, I'm just gonna make it MIT for you. I'm just glad there is someone like my humble work. Thanks.
